version: '3.8'

services:
  redis:
    image: redis:latest # 최신 Redis 이미지 사용
    container_name: redis-container # 컨테이너 이름 지정
    ports:
      - "6379:6379" # 호스트 포트:컨테이너 포트
    volumes:
      - redis_data:/data # 데이터 저장소 볼륨
    command: [ "redis-server" ]

volumes:
  redis_data:
    driver: local